### ISSUE TITLE
Using on github pages & adding packages

### ISSUE THREAD

**Issue by Luke-Symes-Tsy** [georgestagg/shiny-standalone-webr-demo#1]
First off, congrats on this demo, it's really cool!

I am interested in whether the standalone webr shiny app can be run on github pages? I tried to do it on a fork but it seemed to stall after getting to the "Listening on http://127.0.0.1:5081" stage.

I would also like to add some extra packages to the standalone repo, however I'm not quite sure how to run the webr-repo scripts to achieve this - any pointers?

**Comment by ChangwooLim** [comment]
How about https://github.com/orgs/community/discussions/13309#discussioncomment-3844940

But for me, it does not work at Safari

**Comment by georgestagg** [comment]
> I am interested in whether the standalone webR shiny app can be run on github pages?

I have been able to get this to work successfully in another project, the trick is to use the Service Worker to inject the required HTTP headers for Cross-Origin Isolation. Depending on how things are set up, it may require a browser refresh on the first visit to the page, but a short message can be displayed or perhaps the refresh handled automatically.

If I have time, I will look into implementing the trick here.

**Comment by georgestagg** [comment]
I've pushed an update to the `httpuv-serviceworker.js` and `shiny.js` scripts so that the required COI headers are injected by the service worker. This should make things work on GitHub Pages. For example, you can now access the demo at https://georgestagg.github.io/shiny-standalone-webr-demo/

> I would also like to add some extra packages to the standalone repo, however I'm not quite sure how to run the webr-repo scripts to achieve this

Unfortunately, we have not yet written detailed documentation for building R packages with webR. It is an area under active development and things are still in flux, but I expect in time the process will settle down and documentation will come.

If you are willing to experiment and really need other R packages in the short term, I have a Docker image at https://github.com/georgestagg/webr-repo-docker that should be able to build packages. However, please do consider this very experimental for the time being.

**Comment by Luke-Symes-Tsy** [comment]
Many thanks for your help @georgestagg, I managed to get my fork running which is great.

Thanks also for sharing your webr-repo docker image, I will have a go with getting that to run although it might take me a while to figure it out. Understand that it is in flux, and look forward to seeing how things progress!
